"""add api rag core tables

Revision ID: 66d90ab4b719
Revises: 86c214cf500b
Create Date: 2026-05-06 14:44:34.576897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d90ab4b719'
down_revision: Union[str, Sequence[str], None] = '86c214cf500b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('api_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_projects_created_by'), 'api_projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_api_projects_id'), 'api_projects', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('api_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('document_version', sa.String(length=100), nullable=True),
    sa.Column('raw_file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_documents_id'), 'api_documents', ['id'], unique=False)
    op.create_index(op.f('ix_api_documents_project_id'), 'api_documents', ['project_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('api_auth_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=100), nullable=False),
    sa.Column('token_endpoint', sa.String(length=500), nullable=True),
    sa.Column('grant_type', sa.String(length=100), nullable=True),
    sa.Column('header_name', sa.String(length=255), nullable=True),
    sa.Column('description_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['api_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_profiles_document_id'), 'api_auth_profiles', ['document_id'], unique=False)
    op.create_index(op.f('ix_api_auth_profiles_id'), 'api_auth_profiles', ['id'], unique=False)
    op.create_table('api_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('api_reference_id', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_group', sa.String(length=255), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('service_method', sa.String(length=20), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('service_pattern', sa.String(length=100), nullable=True),
    sa.Column('max_timeout', sa.String(length=100), nullable=True),
    sa.Column('api_gateway', sa.String(length=255), nullable=True),
    sa.Column('authentication_type', sa.String(length=100), nullable=True),
    sa.Column('swagger_urls_json', sa.JSON(), nullable=True),
    sa.Column('service_urls_json', sa.JSON(), nullable=True),
    sa.Column('environment_urls_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['api_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_endpoints_api_reference_id'), 'api_endpoints', ['api_reference_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_document_id'), 'api_endpoints', ['document_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_id'), 'api_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_service_name'), 'api_endpoints', ['service_name'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_endpoints', sa.Integer(), nullable=False),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['api_documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_document_id'), 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_project_id'), 'ingestion_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('api_error_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['api_documents.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['api_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_error_codes_document_id'), 'api_error_codes', ['document_id'], unique=False)
    op.create_index(op.f('ix_api_error_codes_endpoint_id'), 'api_error_codes', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_api_error_codes_id'), 'api_error_codes', ['id'], unique=False)
    op.create_table('api_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('parameter_location', sa.String(length=50), nullable=False),
    sa.Column('param_name', sa.String(length=255), nullable=False),
    sa.Column('param_type', sa.String(length=100), nullable=True),
    sa.Column('mandatory_optional', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['api_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_parameters_endpoint_id'), 'api_parameters', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_api_parameters_id'), 'api_parameters', ['id'], unique=False)
    op.create_table('api_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('sample_type', sa.String(length=100), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['api_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_samples_endpoint_id'), 'api_samples', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_api_samples_id'), 'api_samples', ['id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=100), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['api_documents.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['api_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_type'), 'document_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_endpoint_id'), 'document_chunks', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_endpoint_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_type'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_api_samples_id'), table_name='api_samples')
    op.drop_index(op.f('ix_api_samples_endpoint_id'), table_name='api_samples')
    op.drop_table('api_samples')
    op.drop_index(op.f('ix_api_parameters_id'), table_name='api_parameters')
    op.drop_index(op.f('ix_api_parameters_endpoint_id'), table_name='api_parameters')
    op.drop_table('api_parameters')
    op.drop_index(op.f('ix_api_error_codes_id'), table_name='api_error_codes')
    op.drop_index(op.f('ix_api_error_codes_endpoint_id'), table_name='api_error_codes')
    op.drop_index(op.f('ix_api_error_codes_document_id'), table_name='api_error_codes')
    op.drop_table('api_error_codes')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_project_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_document_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_api_endpoints_service_name'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_document_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_api_reference_id'), table_name='api_endpoints')
    op.drop_table('api_endpoints')
    op.drop_index(op.f('ix_api_auth_profiles_id'), table_name='api_auth_profiles')
    op.drop_index(op.f('ix_api_auth_profiles_document_id'), table_name='api_auth_profiles')
    op.drop_table('api_auth_profiles')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_api_documents_project_id'), table_name='api_documents')
    op.drop_index(op.f('ix_api_documents_id'), table_name='api_documents')
    op.drop_table('api_documents')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_api_projects_id'), table_name='api_projects')
    op.drop_index(op.f('ix_api_projects_created_by'), table_name='api_projects')
    op.drop_table('api_projects')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
