from __future__ import annotations

import io
import logging
from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from sqlalchemy.orm import Session

from app.api.deps import get_db, require_admin_or_super_admin
from app.api.v1.admin_demo_logging import log_demo_endpoint_failure
from app.api.v1.endpoints import health as health_endpoints
from app.api.v1.endpoints.admin_demo_readiness import build_demo_readiness_payload
from app.api.v1.endpoints.admin_demo_script import get_demo_script
from app.api.v1.endpoints.audit import list_audit_logs
from app.api.v1.endpoints.feedback import feedback_analytics
from app.api.v1.endpoints.improvements import list_improvement_tasks

router = APIRouter()
logger = logging.getLogger(__name__)


def build_demo_evidence_pack_payload(db: Session, current_user: dict[str, Any]) -> dict[str, Any]:
    readiness = build_demo_readiness_payload(db)
    platform_status = health_endpoints._build_platform_status()
    script = get_demo_script(db=db, _=current_user)
    analytics = feedback_analytics(
        db=db,
        _current_user=current_user,
        knowledge_base_id=None,
        from_date=None,
        to_date=None,
    )
    tasks = list_improvement_tasks(
        db=db,
        _current_user=current_user,
        status_filter=None,
        priority=None,
    )
    audit = list_audit_logs(
        db=db,
        _current_user=current_user,
        action=None,
        entity_type=None,
        knowledge_base_id=None,
        actor_user_id=None,
        from_date=None,
        to_date=None,
    )

    open_tasks = [
        item for item in (tasks.get("items") or []) if item.get("status") in {"open", "in_progress"}
    ]
    recent_audit = (audit.get("items") or [])[:100]

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": {
            "id": current_user.get("id"),
            "email": current_user.get("email"),
            "full_name": current_user.get("full_name"),
        },
        "demo_readiness": readiness,
        "platform_status": platform_status,
        "demo_script": script,
        "feedback_analytics": analytics,
        "open_improvement_tasks": open_tasks,
        "recent_audit_logs": recent_audit,
    }


def _pdf_lines(payload: dict[str, Any]) -> list[str]:
    readiness = payload.get("demo_readiness") or {}
    status = payload.get("platform_status") or {}
    analytics = payload.get("feedback_analytics") or {}
    tasks = payload.get("open_improvement_tasks") or []
    audits = payload.get("recent_audit_logs") or []
    recs = readiness.get("recommendations") or []

    lines: list[str] = [
        "Agentic Enterprise API RAG - Demo Evidence Pack",
        "",
        f"Generated at: {payload.get('generated_at')}",
        f"Generated by: {payload.get('generated_by', {}).get('full_name') or payload.get('generated_by', {}).get('email')}",
        "",
        f"Demo readiness overall: {readiness.get('overall_status')}",
        f"Platform status overall: {status.get('overall_status')}",
        f"Feedback total: {analytics.get('total_feedback')}",
        f"Feedback thumbs up/down: {analytics.get('thumbs_up_count')} / {analytics.get('thumbs_down_count')}",
        "",
        "Open improvement tasks:",
    ]

    if tasks:
        for t in tasks[:20]:
            lines.append(f"- [{t.get('priority')}] {t.get('title')} (status={t.get('status')}, kb={t.get('knowledge_base_name')})")
    else:
        lines.append("- none")

    lines.extend(["", "Recent audit logs:"])
    if audits:
        for a in audits[:25]:
            lines.append(
                f"- {a.get('created_at')} | {a.get('actor_summary')} | {a.get('action')} | {a.get('entity_type')}#{a.get('entity_id')}"
            )
    else:
        lines.append("- none")

    lines.extend(["", "Recommendations:"])
    if recs:
        for r in recs[:20]:
            lines.append(f"- {r}")
    else:
        lines.append("- none")

    return lines


def _render_pdf(payload: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    margin = 40
    y = height - margin

    c.setFont("Helvetica", 10)
    for line in _pdf_lines(payload):
        if y < margin:
            c.showPage()
            c.setFont("Helvetica", 10)
            y = height - margin
        c.drawString(margin, y, str(line)[:150])
        y -= 14

    c.save()
    return buf.getvalue()


@router.get("/demo-evidence-pack")
def demo_evidence_pack(
    db: Session = Depends(get_db),
    current_user: dict[str, Any] = Depends(require_admin_or_super_admin),
) -> dict[str, Any]:
    try:
        return build_demo_evidence_pack_payload(db, current_user)
    except Exception:
        log_demo_endpoint_failure(logger, "GET /admin/demo-evidence-pack")
        raise


@router.get("/demo-evidence-pack/pdf")
def demo_evidence_pack_pdf(
    db: Session = Depends(get_db),
    current_user: dict[str, Any] = Depends(require_admin_or_super_admin),
) -> StreamingResponse:
    try:
        payload = build_demo_evidence_pack_payload(db, current_user)
    except Exception:
        log_demo_endpoint_failure(logger, "GET /admin/demo-evidence-pack/pdf (build)")
        raise
    try:
        pdf = _render_pdf(payload)
    except Exception:
        log_demo_endpoint_failure(logger, "GET /admin/demo-evidence-pack/pdf (render)")
        raise
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    headers = {"Content-Disposition": f'attachment; filename="demo-evidence-pack-{timestamp}.pdf"'}
    return StreamingResponse(io.BytesIO(pdf), media_type="application/pdf", headers=headers)

